name: Build KivyMD APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      # Android environment variables
      ANDROIDNDK: /home/runner/.buildozer/android/platform/android-ndk-r25b
      ANDROIDAPI: 31
      ANDROIDMINAPI: 21
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev git openjdk-17-jdk unzip zip \
        build-essential autoconf libtool pkg-config zlib1g-dev libncurses5-dev \
        libffi-dev libssl-dev

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip install buildozer cython

    - name: Clean old build
      run: rm -rf .buildozer

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-APK
        path: |
          .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/myapp/bin/*.apk
