name: Build KivyMD APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
      ANDROIDNDK: /home/runner/.buildozer/android/platform/android-ndk-r25b
      ANDROIDAPI: 31
      ANDROIDMINAPI: 21
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
      PATH: /home/runner/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH:$PATH

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev git openjdk-17-jdk unzip zip \
        build-essential autoconf libtool pkg-config zlib1g-dev libncurses5-dev \
        libffi-dev libssl-dev wget

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip wheel
        pip install setuptools==65.5.0
        pip install buildozer cython

    - name: Clean old build
      run: rm -rf .buildozer ~/.buildozer

    - name: Install Android cmdline-tools
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
        unzip tools.zip
        rm tools.zip
        mv cmdline-tools latest
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-APK
        path: .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/myapp/bin/*.apk
