name: Build KivyMD APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ANDROID_HOME: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
      ANDROIDNDK: ${{ github.workspace }}/.buildozer/android/platform/android-ndk-r25b
      ANDROIDAPI: 31
      ANDROIDMINAPI: 21
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
      PATH: ${{ github.workspace }}/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH

    steps:
    # Install system dependencies (including tar)
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev git openjdk-17-jdk unzip zip \
        build-essential autoconf libtool pkg-config zlib1g-dev libncurses5-dev \
        libffi-dev libssl-dev wget tar

    # Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Python packages
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install --user cython buildozer

    # Build APK
    - name: Build APK
      run: |
        buildozer -v android debug
